#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_resources.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <infrared.h>
#include <infrared_transmit.h>
#include <infrared_worker.h>
#include <input/input.h>
#include <maxim_crc.h>
#include <one_wire_host.h>
#include <storage/storage.h>
#include <toolbox/saved_struct.h>

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

/* generated by fbt from .png files in images folder */
#include <one_sixteenth_sleep_flipper_icons.h>

#define TAG "1_16_SLEEP"

#define SENSOR_FAMILY_DS18B20 0x28
#define SENSOR_CMD_MATCH_ROM 0x55
#define SENSOR_CMD_CONVERT_T 0x44
#define SENSOR_CMD_READ_SCRATCHPAD 0xBE

#define SENSOR_DISCOVERY_INTERVAL_MS 3000
#define SENSOR_CONVERSION_WAIT_MS 800
#define AUTO_ACTION_GAP_MS 15000

#define IR_B10_ADDR 0x4C4D
#define IR_B10_POWER_CMD 0x47B8
#define IR_B10_FAN_SPEED_CMD 0x45BA
#define IR_B10_FAN_CYCLE_CMD 0x16E9
#define IR_HOLD_SEND_MS 1050
#define IR_FILE_PATH "/ext/infrared/Remote.ir"
#define IR_FILE_NAME_POWER "B10_power"
#define IR_FILE_NAME_FAN_SPEED "Fan_speed"
#define IR_FILE_NAME_FAN_CYCLE "Fan_cycle"

#define INFRARED_SETTINGS_PATH INT_PATH(".infrared.settings")
#define INFRARED_SETTINGS_VERSION (1)
#define INFRARED_SETTINGS_MAGIC (0x1F)

typedef enum {
    IrActionNone = -1,
    IrActionPower = 0,
    IrActionFanSpeed,
    IrActionFanCycle,
} IrAction;

typedef struct {
    uint16_t address;
    uint16_t command;
    bool valid;
} IrFileCode;

typedef struct {
    FuriHalInfraredTxPin tx_pin;
    bool otg_enabled;
} InfraredTxSettings;

typedef struct {
    InputEvent input;
} OneSixteenthSleepEvent;

typedef struct {
    const GpioPin* pin;
    const char* name;
} SensorPinOption;

static const SensorPinOption SENSOR_PINS[] = {
    {.pin = &gpio_ext_pc3, .name = "PC3"},
    {.pin = &gpio_ext_pa7, .name = "PA7"},
    {.pin = &gpio_ext_pc1, .name = "PC1"},
    {.pin = &gpio_ext_pc0, .name = "PC0"},
    {.pin = &gpio_ext_pb2, .name = "PB2"},
    {.pin = &gpio_ext_pb3, .name = "PB3"},
    {.pin = &gpio_ext_pa4, .name = "PA4"},
    {.pin = &gpio_ext_pa6, .name = "PA6"},
};

typedef struct {
    Gui* gui;
    ViewPort* view_port;
    FuriMessageQueue* event_queue;
    FuriMutex* mutex;

    OneWireHost* one_wire;
    int8_t sensor_pin_index;
    bool sensor_found;
    uint8_t sensor_rom[8];
    bool conversion_in_progress;
    uint32_t conversion_started_ms;
    uint32_t last_sensor_probe_ms;
    bool temp_valid;
    float temp_c;

    uint32_t last_ir_ms;
    char last_ir[24];
    FuriHalInfraredTxPin ir_tx_pin;
    InfraredWorker* ir_worker;
    bool ir_tx_active;
    uint32_t manual_ir_started_ms;
    IrAction manual_ir_action;
    bool suppress_ok_release_action;
    bool suppress_left_short_action;
    bool suppress_right_short_action;
    IrFileCode ir_code_power;
    IrFileCode ir_code_fan_speed;
    IrFileCode ir_code_fan_cycle;
    bool ir_file_ready;
    bool ir_otg_enabled;

    bool power_on;
    uint8_t fan_speed;
    uint8_t fan_cycle;

    bool auto_mode;
    float target_c;
    uint32_t last_auto_action_ms;

    bool running;
} OneSixteenthSleepApp;

static uint32_t now_ms(void) {
    return furi_get_tick();
}

static uint8_t next_level(uint8_t current) {
    return (current >= 4) ? 1 : (current + 1);
}

static int forward_steps(uint8_t current, uint8_t target) {
    if(current == target) return 0;
    return (target + 4 - current) % 4;
}

static float clamp_target(float value) {
    if(value < 5.0f) return 5.0f;
    if(value > 45.0f) return 45.0f;
    return value;
}

static uint8_t desired_level_from_temp(float temp_c, float target_c) {
    const float delta = temp_c - target_c;
    if(delta <= 0.40f) return 1;
    if(delta <= 1.20f) return 2;
    if(delta <= 2.50f) return 3;
    return 4;
}

static void app_set_last_ir(OneSixteenthSleepApp* app, const char* label) {
    snprintf(app->last_ir, sizeof(app->last_ir), "%s", label);
    app->last_ir_ms = now_ms();
}

static void trim_ascii(char* s) {
    if(!s) return;
    size_t len = strlen(s);
    while(len > 0 && (s[len - 1] == '\r' || s[len - 1] == '\n' || s[len - 1] == ' ' || s[len - 1] == '\t')) {
        s[--len] = '\0';
    }
    size_t start = 0;
    while(s[start] == ' ' || s[start] == '\t') start++;
    if(start > 0) memmove(s, s + start, len - start + 1);
}

static bool parse_ir_bytes_u16(const char* value, uint16_t* out_u16) {
    unsigned int b0 = 0;
    unsigned int b1 = 0;
    unsigned int b2 = 0;
    unsigned int b3 = 0;
    if(sscanf(value, "%x %x %x %x", &b0, &b1, &b2, &b3) < 2) {
        return false;
    }
    *out_u16 = (uint16_t)(((b0 & 0xFFu) << 8) | (b1 & 0xFFu));
    return true;
}

static void maybe_store_ir_entry(
    OneSixteenthSleepApp* app,
    const char* name,
    bool protocol_ok,
    bool has_addr,
    bool has_cmd,
    uint16_t address,
    uint16_t command) {
    if(!name || !protocol_ok || !has_addr || !has_cmd) return;

    IrFileCode code = {.address = address, .command = command, .valid = true};
    if(strcmp(name, IR_FILE_NAME_POWER) == 0) {
        app->ir_code_power = code;
    } else if(strcmp(name, IR_FILE_NAME_FAN_SPEED) == 0) {
        app->ir_code_fan_speed = code;
    } else if(strcmp(name, IR_FILE_NAME_FAN_CYCLE) == 0) {
        app->ir_code_fan_cycle = code;
    }
}

static void app_load_ir_file_signals(OneSixteenthSleepApp* app) {
    app->ir_file_ready = false;
    app->ir_code_power.valid = false;
    app->ir_code_fan_speed.valid = false;
    app->ir_code_fan_cycle.valid = false;

    Storage* storage = furi_record_open(RECORD_STORAGE);
    if(!storage) {
        FURI_LOG_W(TAG, "Storage unavailable; IR file fallback to constants");
        return;
    }

    File* file = storage_file_alloc(storage);
    if(!file) {
        furi_record_close(RECORD_STORAGE);
        FURI_LOG_W(TAG, "File alloc failed; IR file fallback");
        return;
    }

    bool open_ok = storage_file_open(file, IR_FILE_PATH, FSAM_READ, FSOM_OPEN_EXISTING);
    if(!open_ok) {
        storage_file_free(file);
        furi_record_close(RECORD_STORAGE);
        FURI_LOG_W(TAG, "IR file missing: %s", IR_FILE_PATH);
        return;
    }

    const uint64_t file_size = storage_file_size(file);
    if(file_size == 0 || file_size > 8192) {
        storage_file_close(file);
        storage_file_free(file);
        furi_record_close(RECORD_STORAGE);
        FURI_LOG_W(TAG, "IR file invalid size: %lu", (unsigned long)file_size);
        return;
    }

    char* text = malloc((size_t)file_size + 1u);
    if(!text) {
        storage_file_close(file);
        storage_file_free(file);
        furi_record_close(RECORD_STORAGE);
        FURI_LOG_W(TAG, "IR file alloc failed");
        return;
    }

    const uint16_t read_n = storage_file_read(file, text, (uint16_t)file_size);
    text[read_n] = '\0';

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);

    char current_name[32] = {0};
    bool current_protocol_ok = false;
    bool current_has_addr = false;
    bool current_has_cmd = false;
    uint16_t current_addr = 0;
    uint16_t current_cmd = 0;

    char* cursor = text;
    while(*cursor) {
        char* line = cursor;
        char* nl = strchr(cursor, '\n');
        if(nl) {
            *nl = '\0';
            cursor = nl + 1;
        } else {
            cursor += strlen(cursor);
        }

        trim_ascii(line);
        if(line[0] == '\0' || line[0] == '#') continue;

        if(strncmp(line, "name:", 5) == 0) {
            maybe_store_ir_entry(
                app,
                current_name,
                current_protocol_ok,
                current_has_addr,
                current_has_cmd,
                current_addr,
                current_cmd);

            char* value = line + 5;
            trim_ascii(value);
            snprintf(current_name, sizeof(current_name), "%s", value);
            current_protocol_ok = false;
            current_has_addr = false;
            current_has_cmd = false;
            current_addr = 0;
            current_cmd = 0;
            continue;
        }

        if(strncmp(line, "protocol:", 9) == 0) {
            char* value = line + 9;
            trim_ascii(value);
            current_protocol_ok = (strcmp(value, "NECext") == 0);
            continue;
        }

        if(strncmp(line, "address:", 8) == 0) {
            char* value = line + 8;
            trim_ascii(value);
            current_has_addr = parse_ir_bytes_u16(value, &current_addr);
            continue;
        }

        if(strncmp(line, "command:", 8) == 0) {
            char* value = line + 8;
            trim_ascii(value);
            current_has_cmd = parse_ir_bytes_u16(value, &current_cmd);
            continue;
        }
    }

    maybe_store_ir_entry(
        app,
        current_name,
        current_protocol_ok,
        current_has_addr,
        current_has_cmd,
        current_addr,
        current_cmd);
    free(text);

    app->ir_file_ready =
        app->ir_code_power.valid && app->ir_code_fan_speed.valid && app->ir_code_fan_cycle.valid;
    if(app->ir_file_ready) {
        FURI_LOG_I(
            TAG,
            "IR file loaded %s P:%04X/%04X S:%04X/%04X C:%04X/%04X",
            IR_FILE_PATH,
            app->ir_code_power.address,
            app->ir_code_power.command,
            app->ir_code_fan_speed.address,
            app->ir_code_fan_speed.command,
            app->ir_code_fan_cycle.address,
            app->ir_code_fan_cycle.command);
    } else {
        FURI_LOG_W(
            TAG,
            "IR file incomplete; using constants power=%d speed=%d cycle=%d",
            (int)app->ir_code_power.valid,
            (int)app->ir_code_fan_speed.valid,
            (int)app->ir_code_fan_cycle.valid);
    }
}

static void app_apply_ir_settings(OneSixteenthSleepApp* app) {
    InfraredTxSettings settings = {0};
    const bool loaded = saved_struct_load(
        INFRARED_SETTINGS_PATH,
        &settings,
        sizeof(settings),
        INFRARED_SETTINGS_MAGIC,
        INFRARED_SETTINGS_VERSION);

    if(!loaded) {
        FURI_LOG_W(TAG, "IR settings missing; using default tx pin");
    }

    app->ir_otg_enabled = false;

    if(settings.tx_pin < FuriHalInfraredTxPinMax) {
        app->ir_tx_pin = settings.tx_pin;
        furi_hal_infrared_set_tx_output(app->ir_tx_pin);

        if(app->ir_tx_pin != FuriHalInfraredTxPinInternal && settings.otg_enabled) {
            app->ir_otg_enabled = furi_hal_power_enable_otg();
        }
    } else {
        app->ir_tx_pin = furi_hal_infrared_detect_tx_output();
        furi_hal_infrared_set_tx_output(app->ir_tx_pin);
        if(app->ir_tx_pin != FuriHalInfraredTxPinInternal) {
            app->ir_otg_enabled = furi_hal_power_enable_otg();
        }
    }

    FURI_LOG_I(
        TAG,
        "IR tx pin=%lu otg=%d",
        (unsigned long)app->ir_tx_pin,
        (int)app->ir_otg_enabled);
}

static void app_resolve_ir_code(
    OneSixteenthSleepApp* app,
    IrAction action,
    uint16_t fallback_command,
    uint16_t* out_address,
    uint16_t* out_command,
    bool* out_from_file) {
    uint16_t address = IR_B10_ADDR;
    uint16_t command = fallback_command;
    bool from_file = false;

    if(app->ir_file_ready) {
        const IrFileCode* code = NULL;
        if(action == IrActionPower) code = &app->ir_code_power;
        else if(action == IrActionFanSpeed) code = &app->ir_code_fan_speed;
        else if(action == IrActionFanCycle) code = &app->ir_code_fan_cycle;

        if(code && code->valid) {
            address = code->address;
            command = code->command;
            from_file = true;
        }
    }

    if(out_address) *out_address = address;
    if(out_command) *out_command = command;
    if(out_from_file) *out_from_file = from_file;
}

static void app_ir_tx_start_resolved(
    OneSixteenthSleepApp* app,
    uint16_t address,
    uint16_t command,
    bool from_file,
    const char* label) {
    if(app->ir_tx_active || !app->ir_worker) return;

    furi_hal_infrared_set_tx_output(app->ir_tx_pin);
    InfraredMessage msg = {
        .protocol = InfraredProtocolNECext,
        .address = address,
        .command = command,
        .repeat = false,
    };
    infrared_worker_set_decoded_signal(app->ir_worker, &msg);
    infrared_worker_tx_set_get_signal_callback(
        app->ir_worker, infrared_worker_tx_get_signal_steady_callback, app);
    infrared_worker_tx_start(app->ir_worker);
    app->ir_tx_active = true;
    app->manual_ir_started_ms = now_ms();

    FURI_LOG_I(
        TAG,
        "IR tx start %s src=%s A:%04lX C:%04lX",
        label,
        from_file ? "file" : "const",
        (unsigned long)address,
        (unsigned long)command);

    app_set_last_ir(app, label);
}

static void app_ir_tx_stop(OneSixteenthSleepApp* app) {
    if(!app->ir_tx_active || !app->ir_worker) return;
    infrared_worker_tx_stop(app->ir_worker);
    infrared_worker_tx_set_get_signal_callback(app->ir_worker, NULL, NULL);
    app->ir_tx_active = false;
    FURI_LOG_I(TAG, "IR tx stop");
}

static void app_send_ir(
    OneSixteenthSleepApp* app,
    IrAction action,
    uint16_t fallback_command,
    const char* label) {
    uint16_t address = IR_B10_ADDR;
    uint16_t command = fallback_command;
    bool from_file = false;
    app_resolve_ir_code(app, action, fallback_command, &address, &command, &from_file);

    app_ir_tx_start_resolved(app, address, command, from_file, label);
    furi_delay_ms(IR_HOLD_SEND_MS);
    app_ir_tx_stop(app);
}

static void app_manual_ir_start(
    OneSixteenthSleepApp* app,
    IrAction action,
    uint16_t fallback_command,
    const char* label) {
    if(app->manual_ir_action != IrActionNone || app->ir_tx_active) return;

    uint16_t address = IR_B10_ADDR;
    uint16_t command = fallback_command;
    bool from_file = false;
    app_resolve_ir_code(app, action, fallback_command, &address, &command, &from_file);
    app_ir_tx_start_resolved(app, address, command, from_file, label);
    app->manual_ir_action = action;
}

static void app_manual_ir_stop(OneSixteenthSleepApp* app) {
    if(app->ir_tx_active) {
        const uint32_t elapsed = now_ms() - app->manual_ir_started_ms;
        if(elapsed < IR_HOLD_SEND_MS) {
            furi_delay_ms(IR_HOLD_SEND_MS - elapsed);
        }
    }
    app_ir_tx_stop(app);
    app->manual_ir_action = IrActionNone;
}

static void app_power_toggle(OneSixteenthSleepApp* app) {
    app_send_ir(app, IrActionPower, IR_B10_POWER_CMD, "POWER");
    app->power_on = !app->power_on;
}

static void app_fan_speed_step(OneSixteenthSleepApp* app) {
    app_send_ir(app, IrActionFanSpeed, IR_B10_FAN_SPEED_CMD, "SPD_STEP");
    app->fan_speed = next_level(app->fan_speed);
}

static void app_fan_cycle_step(OneSixteenthSleepApp* app) {
    app_send_ir(app, IrActionFanCycle, IR_B10_FAN_CYCLE_CMD, "CYC_STEP");
    app->fan_cycle = next_level(app->fan_cycle);
}

static void app_set_speed_level(OneSixteenthSleepApp* app, uint8_t target) {
    int steps = forward_steps(app->fan_speed, target);
    for(int i = 0; i < steps; i++) {
        app_fan_speed_step(app);
        furi_delay_ms(180);
    }
}

static void app_set_cycle_level(OneSixteenthSleepApp* app, uint8_t target) {
    int steps = forward_steps(app->fan_cycle, target);
    for(int i = 0; i < steps; i++) {
        app_fan_cycle_step(app);
        furi_delay_ms(180);
    }
}

static void sensor_detach(OneSixteenthSleepApp* app) {
    if(app->one_wire) {
        onewire_host_stop(app->one_wire);
        onewire_host_free(app->one_wire);
        app->one_wire = NULL;
    }
    app->sensor_found = false;
    app->sensor_pin_index = -1;
    app->conversion_in_progress = false;
    app->temp_valid = false;
}

static bool sensor_find_ds18b20(OneSixteenthSleepApp* app) {
    uint8_t rom[8] = {0};

    onewire_host_reset_search(app->one_wire);
    onewire_host_target_search(app->one_wire, SENSOR_FAMILY_DS18B20);

    if(!onewire_host_search(app->one_wire, rom, OneWireHostSearchModeNormal)) {
        return false;
    }

    if(maxim_crc8(rom, 7, MAXIM_CRC8_INIT) != rom[7]) {
        return false;
    }

    memcpy(app->sensor_rom, rom, sizeof(app->sensor_rom));
    return true;
}

static bool sensor_attach_any_pin(OneSixteenthSleepApp* app) {
    sensor_detach(app);

    for(size_t i = 0; i < COUNT_OF(SENSOR_PINS); i++) {
        OneWireHost* host = onewire_host_alloc(SENSOR_PINS[i].pin);
        if(!host) continue;
        onewire_host_start(host);

        app->one_wire = host;
        if(sensor_find_ds18b20(app)) {
            app->sensor_found = true;
            app->sensor_pin_index = (int8_t)i;
            FURI_LOG_I(TAG, "Sensor found on %s", SENSOR_PINS[i].name);
            return true;
        }

        onewire_host_stop(host);
        onewire_host_free(host);
        app->one_wire = NULL;
    }

    FURI_LOG_I(TAG, "Sensor not found on scanned GPIO pins");
    return false;
}

static bool sensor_start_conversion(OneSixteenthSleepApp* app) {
    if(!app->one_wire) return false;
    if(!onewire_host_reset(app->one_wire)) return false;

    onewire_host_write(app->one_wire, SENSOR_CMD_MATCH_ROM);
    onewire_host_write_bytes(app->one_wire, app->sensor_rom, 8);
    onewire_host_write(app->one_wire, SENSOR_CMD_CONVERT_T);
    return true;
}

static bool sensor_read_celsius(OneSixteenthSleepApp* app, float* out_temp_c) {
    uint8_t scratch[9] = {0};

    if(!app->one_wire) return false;
    if(!onewire_host_reset(app->one_wire)) return false;

    onewire_host_write(app->one_wire, SENSOR_CMD_MATCH_ROM);
    onewire_host_write_bytes(app->one_wire, app->sensor_rom, 8);
    onewire_host_write(app->one_wire, SENSOR_CMD_READ_SCRATCHPAD);
    onewire_host_read_bytes(app->one_wire, scratch, sizeof(scratch));

    if(maxim_crc8(scratch, 8, MAXIM_CRC8_INIT) != scratch[8]) {
        return false;
    }

    const int16_t raw = (int16_t)(((uint16_t)scratch[1] << 8) | scratch[0]);
    *out_temp_c = (float)raw / 16.0f;
    return true;
}

static void sensor_service(OneSixteenthSleepApp* app) {
    const uint32_t now = now_ms();

    if(!app->sensor_found || !app->one_wire) {
        if(now - app->last_sensor_probe_ms < SENSOR_DISCOVERY_INTERVAL_MS) return;

        app->last_sensor_probe_ms = now;
        app->sensor_found = sensor_attach_any_pin(app);
        app->temp_valid = false;
        app->conversion_in_progress = false;

        if(app->sensor_found && sensor_start_conversion(app)) {
            app->conversion_in_progress = true;
            app->conversion_started_ms = now;
            app_set_last_ir(app, "SENSOR_OK");
        }
        return;
    }

    if(!app->conversion_in_progress) {
        if(sensor_start_conversion(app)) {
            app->conversion_in_progress = true;
            app->conversion_started_ms = now;
        } else {
            sensor_detach(app);
        }
        return;
    }

    if(now - app->conversion_started_ms < SENSOR_CONVERSION_WAIT_MS) return;

    float temp_c = 0.0f;
    if(sensor_read_celsius(app, &temp_c)) {
        app->temp_c = temp_c;
        app->temp_valid = true;
    } else {
        sensor_detach(app);
    }

    app->conversion_in_progress = false;
    app->last_sensor_probe_ms = now;
}

static void auto_control_tick(OneSixteenthSleepApp* app) {
    if(!app->auto_mode || !app->temp_valid) return;

    const uint32_t now = now_ms();
    if(now - app->last_auto_action_ms < AUTO_ACTION_GAP_MS) return;

    if(app->temp_c <= app->target_c) {
        if(app->power_on) {
            app_power_toggle(app);
            app_set_last_ir(app, "AUTO_OFF");
            app->last_auto_action_ms = now;
        }
        return;
    }

    if(!app->power_on) {
        app_power_toggle(app);
        app_set_last_ir(app, "AUTO_ON");
        app->last_auto_action_ms = now;
        return;
    }

    const uint8_t desired = desired_level_from_temp(app->temp_c, app->target_c);

    if(app->fan_speed != desired) {
        app_set_speed_level(app, desired);
        app_set_last_ir(app, "AUTO_SPD");
        app->last_auto_action_ms = now;
        return;
    }

    if(app->fan_cycle != desired) {
        app_set_cycle_level(app, desired);
        app_set_last_ir(app, "AUTO_CYC");
        app->last_auto_action_ms = now;
        return;
    }
}

static void input_callback(InputEvent* input_event, void* context) {
    furi_assert(context);
    OneSixteenthSleepApp* app = context;

    OneSixteenthSleepEvent event = {.input = *input_event};
    furi_message_queue_put(app->event_queue, &event, FuriWaitForever);
}

static void draw_callback(Canvas* canvas, void* context) {
    furi_assert(context);
    OneSixteenthSleepApp* app = context;

    if(furi_mutex_acquire(app->mutex, 25) != FuriStatusOk) return;

    canvas_clear(canvas);
    canvas_set_font(canvas, FontSecondary);

    char line[64];
    canvas_draw_str(canvas, 2, 9, "One Sixteenth Sleep");

    if(app->temp_valid) {
        snprintf(line, sizeof(line), "Temp: %.2f C", (double)app->temp_c);
    } else {
        snprintf(line, sizeof(line), "Temp: --.-- C");
    }
    canvas_draw_str(canvas, 2, 19, line);

    const char* pin_name = (app->sensor_pin_index >= 0) ? SENSOR_PINS[app->sensor_pin_index].name : "--";
    snprintf(line, sizeof(line), "Sensor: %s (%s)", app->sensor_found ? "OK" : "NO", pin_name);
    canvas_draw_str(canvas, 2, 29, line);

    snprintf(
        line,
        sizeof(line),
        "Target: %.1fC Auto:%s",
        (double)app->target_c,
        app->auto_mode ? "ON" : "OFF");
    canvas_draw_str(canvas, 2, 39, line);

    snprintf(
        line,
        sizeof(line),
        "Pwr:%s Spd:%u Cyc:%u",
        app->power_on ? "ON" : "OFF",
        app->fan_speed,
        app->fan_cycle);
    canvas_draw_str(canvas, 2, 49, line);

    snprintf(line, sizeof(line), "Last: %s", app->last_ir);
    canvas_draw_str(canvas, 2, 59, line);

    furi_mutex_release(app->mutex);
}

static void handle_input_event(OneSixteenthSleepApp* app, const InputEvent* input) {
    if(input->type == InputTypeShort) {
        // Fallback path for injected "short" events (CLI automation).
        if(input->key == InputKeyOk) {
            FURI_LOG_I(TAG, "Input short OK");
            app_power_toggle(app);
            return;
        }
        if(input->key == InputKeyLeft) {
            if(app->suppress_left_short_action) {
                app->suppress_left_short_action = false;
                return;
            }
            FURI_LOG_I(TAG, "Input short LEFT");
            app_fan_speed_step(app);
            return;
        }
        if(input->key == InputKeyRight) {
            if(app->suppress_right_short_action) {
                app->suppress_right_short_action = false;
                return;
            }
            FURI_LOG_I(TAG, "Input short RIGHT");
            app_fan_cycle_step(app);
            return;
        }
        if(input->key == InputKeyUp) {
            app->target_c = clamp_target(app->target_c + 0.5f);
            app_set_last_ir(app, "TARGET+");
            return;
        }
        if(input->key == InputKeyDown) {
            app->target_c = clamp_target(app->target_c - 0.5f);
            app_set_last_ir(app, "TARGET-");
            return;
        }
        if(input->key == InputKeyBack) {
            app->running = false;
            return;
        }
    }

    if(input->type == InputTypeLong && input->key == InputKeyOk) {
        if(app->manual_ir_action == IrActionPower) {
            // Keep long-hold behavior for IR POWER send; don't repurpose this hold.
            return;
        }
        FURI_LOG_I(TAG, "Input long OK");
        app->auto_mode = !app->auto_mode;
        app_set_last_ir(app, app->auto_mode ? "AUTO_ON" : "AUTO_OFF");
        app->last_auto_action_ms = 0;
        return;
    }

    if(input->type == InputTypePress) {
        if(input->key == InputKeyLeft) {
            FURI_LOG_I(TAG, "Input press LEFT -> TX start");
            app_manual_ir_start(app, IrActionFanSpeed, IR_B10_FAN_SPEED_CMD, "SPD_STEP");
            return;
        }
        if(input->key == InputKeyRight) {
            FURI_LOG_I(TAG, "Input press RIGHT -> TX start");
            app_manual_ir_start(app, IrActionFanCycle, IR_B10_FAN_CYCLE_CMD, "CYC_STEP");
            return;
        }
        if(input->key == InputKeyBack) {
            app->running = false;
            return;
        }
    }

    if(input->type == InputTypeRelease) {
        if(input->key == InputKeyLeft && app->manual_ir_action == IrActionFanSpeed) {
            app_manual_ir_stop(app);
            app->fan_speed = next_level(app->fan_speed);
            app->suppress_left_short_action = true;
            return;
        }
        if(input->key == InputKeyRight && app->manual_ir_action == IrActionFanCycle) {
            app_manual_ir_stop(app);
            app->fan_cycle = next_level(app->fan_cycle);
            app->suppress_right_short_action = true;
            return;
        }
    }
}

int32_t one_sixteenth_sleep_flipper_app(void* p) {
    UNUSED(p);

    OneSixteenthSleepApp* app = malloc(sizeof(OneSixteenthSleepApp));
    if(!app) return 255;
    memset(app, 0, sizeof(OneSixteenthSleepApp));

    app->mutex = furi_mutex_alloc(FuriMutexTypeNormal);
    app->event_queue = furi_message_queue_alloc(8, sizeof(OneSixteenthSleepEvent));
    app->view_port = view_port_alloc();
    app->gui = furi_record_open(RECORD_GUI);

    app->one_wire = NULL;
    app->sensor_pin_index = -1;
    app_apply_ir_settings(app);
    app->ir_worker = infrared_worker_alloc();
    app->ir_tx_active = false;
    app->manual_ir_started_ms = 0;
    app->manual_ir_action = IrActionNone;
    app->suppress_ok_release_action = false;
    app->suppress_left_short_action = false;
    app->suppress_right_short_action = false;
    app->ir_file_ready = false;

    app->power_on = true;
    app->fan_speed = 1;
    app->fan_cycle = 1;
    app->target_c = 20.0f;
    app->auto_mode = false;
    app->last_auto_action_ms = now_ms();
    app->running = true;
    snprintf(app->last_ir, sizeof(app->last_ir), "BOOT");
    app_load_ir_file_signals(app);

    view_port_draw_callback_set(app->view_port, draw_callback, app);
    view_port_input_callback_set(app->view_port, input_callback, app);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    FURI_LOG_I(TAG, "App started");

    while(app->running) {
        OneSixteenthSleepEvent event;
        if(furi_message_queue_get(app->event_queue, &event, 100) == FuriStatusOk) {
            if(furi_mutex_acquire(app->mutex, FuriWaitForever) == FuriStatusOk) {
                handle_input_event(app, &event.input);
                furi_mutex_release(app->mutex);
            }
        }

        if(furi_mutex_acquire(app->mutex, FuriWaitForever) == FuriStatusOk) {
            sensor_service(app);
            auto_control_tick(app);
            furi_mutex_release(app->mutex);
        }

        view_port_update(app->view_port);
    }

    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);

    sensor_detach(app);
    app_manual_ir_stop(app);
    if(app->ir_worker) infrared_worker_free(app->ir_worker);
    if(app->ir_otg_enabled) {
        furi_hal_power_disable_otg();
        app->ir_otg_enabled = false;
    }

    furi_message_queue_free(app->event_queue);
    furi_mutex_free(app->mutex);
    furi_record_close(RECORD_GUI);

    free(app);
    FURI_LOG_I(TAG, "App stopped");
    return 0;
}
