#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_resources.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <infrared.h>
#include <infrared_transmit.h>
#include <input/input.h>
#include <maxim_crc.h>
#include <one_wire_host.h>

#include <stdio.h>
#include <string.h>

/* generated by fbt from .png files in images folder */
#include <one_sixteenth_sleep_flipper_icons.h>

#define TAG "1_16_SLEEP"

#define SENSOR_FAMILY_DS18B20 0x28
#define SENSOR_CMD_MATCH_ROM 0x55
#define SENSOR_CMD_CONVERT_T 0x44
#define SENSOR_CMD_READ_SCRATCHPAD 0xBE

#define SENSOR_DISCOVERY_INTERVAL_MS 3000
#define SENSOR_CONVERSION_WAIT_MS 800
#define AUTO_ACTION_GAP_MS 15000

#define IR_B10_ADDR 0x4C4D
#define IR_B10_POWER_CMD 0x47B8
#define IR_B10_FAN_SPEED_CMD 0x45BA
#define IR_B10_FAN_CYCLE_CMD 0x16E9

typedef struct {
    InputEvent input;
} OneSixteenthSleepEvent;

typedef struct {
    Gui* gui;
    ViewPort* view_port;
    FuriMessageQueue* event_queue;
    FuriMutex* mutex;

    OneWireHost* one_wire;
    bool sensor_found;
    uint8_t sensor_rom[8];
    bool conversion_in_progress;
    uint32_t conversion_started_ms;
    uint32_t last_sensor_probe_ms;
    bool temp_valid;
    float temp_c;

    uint32_t last_ir_ms;
    char last_ir[24];

    bool power_on;
    uint8_t fan_speed;
    uint8_t fan_cycle;

    bool auto_mode;
    float target_c;
    uint32_t last_auto_action_ms;

    bool running;
} OneSixteenthSleepApp;

static uint32_t now_ms(void) {
    return furi_get_tick();
}

static uint8_t next_level(uint8_t current) {
    return (current >= 4) ? 1 : (current + 1);
}

static int forward_steps(uint8_t current, uint8_t target) {
    if(current == target) return 0;
    return (target + 4 - current) % 4;
}

static float clamp_target(float value) {
    if(value < 5.0f) return 5.0f;
    if(value > 45.0f) return 45.0f;
    return value;
}

static uint8_t desired_level_from_temp(float temp_c, float target_c) {
    const float delta = temp_c - target_c;
    if(delta <= 0.40f) return 1;
    if(delta <= 1.20f) return 2;
    if(delta <= 2.50f) return 3;
    return 4;
}

static void app_set_last_ir(OneSixteenthSleepApp* app, const char* label) {
    snprintf(app->last_ir, sizeof(app->last_ir), "%s", label);
    app->last_ir_ms = now_ms();
}

static void app_send_ir(OneSixteenthSleepApp* app, uint16_t command, const char* label) {
    InfraredMessage msg = {
        .protocol = InfraredProtocolNECext,
        .address = IR_B10_ADDR,
        .command = command,
        .repeat = false,
    };

    infrared_send(&msg, 3);

    app_set_last_ir(app, label);
}

static void app_power_toggle(OneSixteenthSleepApp* app) {
    app_send_ir(app, IR_B10_POWER_CMD, "POWER");
    app->power_on = !app->power_on;
}

static void app_fan_speed_step(OneSixteenthSleepApp* app) {
    app_send_ir(app, IR_B10_FAN_SPEED_CMD, "SPD_STEP");
    app->fan_speed = next_level(app->fan_speed);
}

static void app_fan_cycle_step(OneSixteenthSleepApp* app) {
    app_send_ir(app, IR_B10_FAN_CYCLE_CMD, "CYC_STEP");
    app->fan_cycle = next_level(app->fan_cycle);
}

static void app_set_speed_level(OneSixteenthSleepApp* app, uint8_t target) {
    int steps = forward_steps(app->fan_speed, target);
    for(int i = 0; i < steps; i++) {
        app_fan_speed_step(app);
        furi_delay_ms(180);
    }
}

static void app_set_cycle_level(OneSixteenthSleepApp* app, uint8_t target) {
    int steps = forward_steps(app->fan_cycle, target);
    for(int i = 0; i < steps; i++) {
        app_fan_cycle_step(app);
        furi_delay_ms(180);
    }
}

static bool sensor_find_ds18b20(OneSixteenthSleepApp* app) {
    uint8_t rom[8] = {0};

    onewire_host_reset_search(app->one_wire);
    onewire_host_target_search(app->one_wire, SENSOR_FAMILY_DS18B20);

    if(!onewire_host_search(app->one_wire, rom, OneWireHostSearchModeNormal)) {
        return false;
    }

    if(maxim_crc8(rom, 7, MAXIM_CRC8_INIT) != rom[7]) {
        return false;
    }

    memcpy(app->sensor_rom, rom, sizeof(app->sensor_rom));
    return true;
}

static bool sensor_start_conversion(OneSixteenthSleepApp* app) {
    if(!onewire_host_reset(app->one_wire)) {
        return false;
    }

    onewire_host_write(app->one_wire, SENSOR_CMD_MATCH_ROM);
    onewire_host_write_bytes(app->one_wire, app->sensor_rom, 8);
    onewire_host_write(app->one_wire, SENSOR_CMD_CONVERT_T);
    return true;
}

static bool sensor_read_celsius(OneSixteenthSleepApp* app, float* out_temp_c) {
    uint8_t scratch[9] = {0};

    if(!onewire_host_reset(app->one_wire)) {
        return false;
    }

    onewire_host_write(app->one_wire, SENSOR_CMD_MATCH_ROM);
    onewire_host_write_bytes(app->one_wire, app->sensor_rom, 8);
    onewire_host_write(app->one_wire, SENSOR_CMD_READ_SCRATCHPAD);
    onewire_host_read_bytes(app->one_wire, scratch, sizeof(scratch));

    if(maxim_crc8(scratch, 8, MAXIM_CRC8_INIT) != scratch[8]) {
        return false;
    }

    const int16_t raw = (int16_t)(((uint16_t)scratch[1] << 8) | scratch[0]);
    *out_temp_c = (float)raw / 16.0f;
    return true;
}

static void sensor_service(OneSixteenthSleepApp* app) {
    const uint32_t now = now_ms();

    if(!app->sensor_found) {
        if(now - app->last_sensor_probe_ms < SENSOR_DISCOVERY_INTERVAL_MS) {
            return;
        }

        app->last_sensor_probe_ms = now;
        app->sensor_found = sensor_find_ds18b20(app);
        app->temp_valid = false;
        app->conversion_in_progress = false;

        if(app->sensor_found) {
            if(sensor_start_conversion(app)) {
                app->conversion_in_progress = true;
                app->conversion_started_ms = now;
                app_set_last_ir(app, "SENSOR_OK");
            } else {
                app->sensor_found = false;
            }
        }
        return;
    }

    if(!app->conversion_in_progress) {
        if(sensor_start_conversion(app)) {
            app->conversion_in_progress = true;
            app->conversion_started_ms = now;
        } else {
            app->sensor_found = false;
            app->temp_valid = false;
        }
        return;
    }

    if(now - app->conversion_started_ms < SENSOR_CONVERSION_WAIT_MS) {
        return;
    }

    float temp_c = 0.0f;
    if(sensor_read_celsius(app, &temp_c)) {
        app->temp_c = temp_c;
        app->temp_valid = true;
    } else {
        app->sensor_found = false;
        app->temp_valid = false;
    }

    app->conversion_in_progress = false;
    app->last_sensor_probe_ms = now;
}

static void auto_control_tick(OneSixteenthSleepApp* app) {
    if(!app->auto_mode || !app->temp_valid) return;

    const uint32_t now = now_ms();
    if(now - app->last_auto_action_ms < AUTO_ACTION_GAP_MS) return;

    if(app->temp_c <= app->target_c) {
        if(app->power_on) {
            app_power_toggle(app);
            app_set_last_ir(app, "AUTO_OFF");
            app->last_auto_action_ms = now;
        }
        return;
    }

    if(!app->power_on) {
        app_power_toggle(app);
        app_set_last_ir(app, "AUTO_ON");
        app->last_auto_action_ms = now;
        return;
    }

    const uint8_t desired = desired_level_from_temp(app->temp_c, app->target_c);

    if(app->fan_speed != desired) {
        app_set_speed_level(app, desired);
        app_set_last_ir(app, "AUTO_SPD");
        app->last_auto_action_ms = now;
        return;
    }

    if(app->fan_cycle != desired) {
        app_set_cycle_level(app, desired);
        app_set_last_ir(app, "AUTO_CYC");
        app->last_auto_action_ms = now;
        return;
    }
}

static void input_callback(InputEvent* input_event, void* context) {
    furi_assert(context);
    OneSixteenthSleepApp* app = context;

    OneSixteenthSleepEvent event = {.input = *input_event};
    furi_message_queue_put(app->event_queue, &event, FuriWaitForever);
}

static void draw_callback(Canvas* canvas, void* context) {
    furi_assert(context);
    OneSixteenthSleepApp* app = context;

    if(furi_mutex_acquire(app->mutex, 25) != FuriStatusOk) {
        return;
    }

    canvas_clear(canvas);
    canvas_set_font(canvas, FontSecondary);

    char line[64];
    canvas_draw_str(canvas, 2, 9, "One Sixteenth Sleep");

    if(app->temp_valid) {
        snprintf(line, sizeof(line), "Temp: %.2f C", (double)app->temp_c);
    } else {
        snprintf(line, sizeof(line), "Temp: --.-- C");
    }
    canvas_draw_str(canvas, 2, 19, line);

    snprintf(line, sizeof(line), "Sensor: %s (PA7)", app->sensor_found ? "OK" : "NO");
    canvas_draw_str(canvas, 2, 29, line);

    snprintf(
        line,
        sizeof(line),
        "Target: %.1fC Auto:%s",
        (double)app->target_c,
        app->auto_mode ? "ON" : "OFF");
    canvas_draw_str(canvas, 2, 39, line);

    snprintf(
        line,
        sizeof(line),
        "Pwr:%s Spd:%u Cyc:%u",
        app->power_on ? "ON" : "OFF",
        app->fan_speed,
        app->fan_cycle);
    canvas_draw_str(canvas, 2, 49, line);

    snprintf(line, sizeof(line), "Last: %s", app->last_ir);
    canvas_draw_str(canvas, 2, 59, line);

    furi_mutex_release(app->mutex);
}

static void handle_input_event(OneSixteenthSleepApp* app, const InputEvent* input) {
    if(input->type != InputTypeShort && input->type != InputTypeLong) {
        return;
    }

    if(input->type == InputTypeShort) {
        switch(input->key) {
        case InputKeyBack:
            app->running = false;
            return;
        case InputKeyOk:
            app_power_toggle(app);
            return;
        case InputKeyLeft:
            app_fan_speed_step(app);
            return;
        case InputKeyRight:
            app_fan_cycle_step(app);
            return;
        case InputKeyUp:
            app->target_c = clamp_target(app->target_c + 0.5f);
            app_set_last_ir(app, "TARGET+");
            return;
        case InputKeyDown:
            app->target_c = clamp_target(app->target_c - 0.5f);
            app_set_last_ir(app, "TARGET-");
            return;
        default:
            return;
        }
    }

    if(input->type == InputTypeLong && input->key == InputKeyOk) {
        app->auto_mode = !app->auto_mode;
        app_set_last_ir(app, app->auto_mode ? "AUTO_ON" : "AUTO_OFF");
        app->last_auto_action_ms = 0;
    }
}

int32_t one_sixteenth_sleep_flipper_app(void* p) {
    UNUSED(p);

    OneSixteenthSleepApp* app = malloc(sizeof(OneSixteenthSleepApp));
    if(!app) {
        return 255;
    }
    memset(app, 0, sizeof(OneSixteenthSleepApp));

    app->mutex = furi_mutex_alloc(FuriMutexTypeNormal);
    app->event_queue = furi_message_queue_alloc(8, sizeof(OneSixteenthSleepEvent));
    app->view_port = view_port_alloc();
    app->gui = furi_record_open(RECORD_GUI);

    app->one_wire = onewire_host_alloc(&gpio_ext_pa7);
    if(app->one_wire) {
        onewire_host_start(app->one_wire);
    }

    app->power_on = true;
    app->fan_speed = 1;
    app->fan_cycle = 1;
    app->target_c = 20.0f;
    app->auto_mode = false;
    app->last_auto_action_ms = now_ms();
    app->running = true;
    snprintf(app->last_ir, sizeof(app->last_ir), "BOOT");

    view_port_draw_callback_set(app->view_port, draw_callback, app);
    view_port_input_callback_set(app->view_port, input_callback, app);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    FURI_LOG_I(TAG, "App started");

    while(app->running) {
        OneSixteenthSleepEvent event;
        if(furi_message_queue_get(app->event_queue, &event, 100) == FuriStatusOk) {
            if(furi_mutex_acquire(app->mutex, FuriWaitForever) == FuriStatusOk) {
                handle_input_event(app, &event.input);
                furi_mutex_release(app->mutex);
            }
        }

        if(furi_mutex_acquire(app->mutex, FuriWaitForever) == FuriStatusOk) {
            if(app->one_wire) {
                sensor_service(app);
            }
            auto_control_tick(app);
            furi_mutex_release(app->mutex);
        }

        view_port_update(app->view_port);
    }

    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);

    if(app->one_wire) {
        onewire_host_stop(app->one_wire);
        onewire_host_free(app->one_wire);
    }

    furi_message_queue_free(app->event_queue);
    furi_mutex_free(app->mutex);
    furi_record_close(RECORD_GUI);

    free(app);
    FURI_LOG_I(TAG, "App stopped");
    return 0;
}
